use gala-spins;
-- gdpr messages
CALL add_translation('playtech.mobile.system.gdpr.privacypolicy.notification.title','Updated Policies',NULL);
CALL add_translation('playtech.mobile.system.gdpr.privacypolicy.active.notification.content','<p class="lci-cookie-banner__text">We&#39;ve updated our <a data-help-center-link-alias="privacy" href="/help-centre?page=privacy" target="_blank">Privacy Policy</a> and <a href="/help-centre?page=cookiePolicy" target="_blank" data-help-center-link-alias="cookiePolicy">Cookie Policy</a> to provide more detailed information as required by new EU privacy laws. To view or edit your contact preferences, please go to <a href="/my-account/my-details">My Account</a></p>',NULL);
CALL add_translation('playtech.mobile.system.gdpr.privacypolicy.inactive.notification.content.above.link','<p>We&#39;ve updated our <a data-help-center-link-alias="privacy" href="/help-centre?page=privacy" target="_blank">Privacy Policy</a> and <a href="/help-centre?page=cookiePolicy" target="_blank" data-help-center-link-alias="cookiePolicy">Cookie Policy</a> to provide more detailed information as required by new EU privacy laws.</p>',NULL);
CALL add_translation('playtech.mobile.system.gdpr.privacypolicy.inactive.notification.content.next.to.link','Yes please! I would like to receive information about the latest offers and promotions from Gala Bingo. <a class="fn-goto-preferences">Manage My Preferences</a>',NULL);
-- splash
CALL add_translation('playtech.mobile.system.login-message.opt-in.inactive.header-title','BE SPINCREDIBLE',NULL);
CALL add_translation('playtech.mobile.system.login-message.opt-in.inactive.header-subtitle','Stay on our files and get the latest Gala Spins news and offers first!<br>You’ll feel Spintelligent knowing that you’re signed up for all the information you need at Gala Spins.',NULL);
CALL add_translation('playtech.mobile.system.login-message.opt-in.inactive.body-button.accept','Yes, I’d like to hear from you',NULL);
CALL add_translation('playtech.mobile.system.login-message.opt-in.inactive.body-button.decline','No, thanks',NULL);
CALL add_translation('playtech.mobile.system.gdpr.privacypolicy.splash.footer','We&#39;ve updated our <a class="trusted-link lci-gala-splash__footer-link" href="/help-centre?page=privacy" target="_blank">Privacy Policy</a> and <a class="trusted-link lci-gala-splash__footer-link" href="/help-centre?page=cookiePolicy" target="_blank">Cookie Policy</a> to provide more detailed information as requested by new EU privacy laws. Update your settings at any time in <a class="trusted-link lci-gala-splash__footer-link" href="/my-account/my-details">Account Preferences</a>.',NULL);
-- cookie
CALL add_translation('playtech.mobile.system.gdpr.cookie.banner.content','<p class="lci-cookie-banner__text">We&#39;ve updated our <a data-help-center-link-alias="privacy" href="/help-centre?page=privacy" target="_blank">Privacy Policy</a> and <a href="/help-centre?page=cookiePolicy" target="_blank" data-help-center-link-alias="cookiePolicy">Cookie Policy</a> to provide more detailed information as required by new EU privacy laws.</p>',NULL);
CALL add_translation('playtech.mobile.system.gdpr.cookie.banner.button.text','Accept',NULL);
